//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PlanNumber", ReplyAction="http://tempuri.org/IService1/PlanNumberResponse")]
        double PlanNumber(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PlanNumber", ReplyAction="http://tempuri.org/IService1/PlanNumberResponse")]
        System.Threading.Tasks.Task<double> PlanNumberAsync(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/JianNumber", ReplyAction="http://tempuri.org/IService1/JianNumberResponse")]
        double JianNumber(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/JianNumber", ReplyAction="http://tempuri.org/IService1/JianNumberResponse")]
        System.Threading.Tasks.Task<double> JianNumberAsync(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChengNumber", ReplyAction="http://tempuri.org/IService1/ChengNumberResponse")]
        double ChengNumber(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChengNumber", ReplyAction="http://tempuri.org/IService1/ChengNumberResponse")]
        System.Threading.Tasks.Task<double> ChengNumberAsync(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChuNummber", ReplyAction="http://tempuri.org/IService1/ChuNummberResponse")]
        double ChuNummber(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChuNummber", ReplyAction="http://tempuri.org/IService1/ChuNummberResponse")]
        System.Threading.Tasks.Task<double> ChuNummberAsync(double num1, double num2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCF.ServiceReference1.IService1>, WCF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double PlanNumber(double num1, double num2) {
            return base.Channel.PlanNumber(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> PlanNumberAsync(double num1, double num2) {
            return base.Channel.PlanNumberAsync(num1, num2);
        }
        
        public double JianNumber(double num1, double num2) {
            return base.Channel.JianNumber(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> JianNumberAsync(double num1, double num2) {
            return base.Channel.JianNumberAsync(num1, num2);
        }
        
        public double ChengNumber(double num1, double num2) {
            return base.Channel.ChengNumber(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> ChengNumberAsync(double num1, double num2) {
            return base.Channel.ChengNumberAsync(num1, num2);
        }
        
        public double ChuNummber(double num1, double num2) {
            return base.Channel.ChuNummber(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> ChuNummberAsync(double num1, double num2) {
            return base.Channel.ChuNummberAsync(num1, num2);
        }
    }
}
